spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://localhost:3306/admindb?useSSL=false&serverTimezone=UTC
    username: root
    password: root1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8085